In [1]:
# creating a list called names and assigning it the value of A AND B
names = ["A", "B"]

# Then I print out the names list to the console
print(names)


['A', 'B']


In [2]:
# Now I will print the first element of the names list to the console
print(names[0]) 

A


In [3]:
# append the letter C to the names list
names.append("C")

In [4]:
# print the names list again to see the change
# the output should now be ["A", "B", "C"]
# the append method adds an element to the end of the list
print(names)

['A', 'B', 'C']


In [5]:
# the len() function returns the number of elements in a list
print(len(names))
# the len() function should return 3 because there are 3 elements in the names list
# the output should be 3


3


In [6]:
# Concatenating lists
# I will create another list called more_names and assign it the value of D AND E
more_names = ["D", "E"]
# Now I will concatenate the names list and the more_names list and assign it to a new variable called all_names
all_names = names + more_names
# Now I will print the all_names list to the console
print(all_names)
# the output should be ["A", "B", "C", "D", "E"]

['A', 'B', 'C', 'D', 'E']


In [7]:
# Two common ways to create an empty list in Python:
# 1. Using empty square brackets:
empty_list1 = []
# 2. Using the list() constructor:
empty_list2 = list()    
# Both empty_list1 and empty_list2 are now empty lists that can be used to store data.


In [8]:
# empty_list1 and empty_list2 are both empty lists that can be used to store data.
# now  I will create a list that contains different data types
mixed_list = ["Hello", 42, 3.14, True]
# the mixed_list contains a string, an integer, a float, and a boolean value
# I will print the mixed_list to the console
print(mixed_list)
# the output should be ["Hello", 42, 3.14, True]
# the data types in the mixed_list are string, integer, float, and boolean.
# i can also include other lists as elements in a list, creating a nested list
nested_list = [1, 2, [3, 4], 5]
# the nested_list contains an integer, another list, and another integer
# I will print the nested_list to the console
print(nested_list)


['Hello', 42, 3.14, True]
[1, 2, [3, 4], 5]


In [9]:
# now on to list slicing
# list slicing allows you to access a portion of a list by specifying a range of indices
# the syntax for list slicing is list[start:stop:step]
# start is the index where the slice starts (inclusive)
# stop is the index where the slice ends (exclusive)
# step is the number of indices to skip (optional)
# I will create a list of numbers from 0 to 9
numbers = list(range(10))
# the numbers list should contain [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# I will print the numbers list to the console  
print(numbers)
# the output should be [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# Now I will slice the numbers list to get the first 5 elements
first_five = numbers[0:5]
# the first_five list should contain [0, 1, 2, 3, 4]
# I will print the first_five list to the console
# the slice operator [0:5] means start at index 0 and end at index 5 (exclusive), so it will include indices 0, 1, 2, 3, and 4
print(first_five)
# the output should be [0, 1, 2, 3, 4]
# Now I will slice the numbers list to get the last 5 elements
last_five = numbers[5:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4]


In [10]:
#[:] is a common slicing syntax that means to include all elements from the start to the end of the list.
# So numbers[:] will create a new list that is a copy of the original numbers list, containing all the same elements.
all_numbers = numbers[:]
# I will print the all_numbers list to the console
print(all_numbers)  

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
# 2 arrays are equal if they contain the same elements in the same order
# I will check if the numbers list is equal to the all_numbers list
# [:] creates a new list that is a copy of the original list, so numbers[:] and all_numbers should be equal
# [:,0] is a common slicing syntax that means to include all elements from the start to the end of the list, but only for the first column (index 0) if the list is a 2D list (list of lists).
# Since numbers is a 1D list, the [:,0] syntax is not applicable
print(numbers == all_numbers)
# the output should be True because numbers and all_numbers contain the same elements in the same order
# [0,:] is a common slicing syntax that means to include all elements from the start to the end of the list, but only for the first row (index 0) if the list is a 2D list (list of lists).
# Since numbers is a 1D list, the [0,:] syntax is not applicable


True


In [12]:
# negative indices can also be used in list slicing to access elements from the end of the list
# for example, numbers[-1] will give you the last element of the numbers list, which is 9
print(numbers[-1])
# the output should be 9 because it is the last element of the numbers list


9


In [13]:
# numbers[-3:] will give you the last 3 elements of the numbers list, which are [7, 8, 9]
print(numbers[-3:])

[7, 8, 9]


In [14]:
# numbers[3:-2] will give you the elements from index 3 to index -2 (exclusive), which are [3, 4, 5, 6]
print(numbers[3:-2])

[3, 4, 5, 6, 7]


In [15]:
#tuples
# A tuple is similar to a list in Python, but it is immutable (cannot be changed after creation)
my_tuple = (1, 2, 3)
# I will print the my_tuple to the console
print(my_tuple)

(1, 2, 3)


In [16]:
#a tuple is defined using parentheses () instead of square brackets [] like a list
# we will do one for A AND B
my_tuple2 = ("A", "B")
print(my_tuple2)
# the output should be ("A", "B")
# Tuples and lists are both used to store collections of data, but tuples are immutable while lists are mutable. This means that you cannot change the elements of a tuple after it has been created, while you can change the elements of a list.
# so if I try to change an element of my_tuple2, I will get an error
# my_tuple2[0] = "C"  # This will raise a TypeError
#my_tuple2[0] = "C"  # This will raise a TypeError because tuples are immutable and cannot be changed after creation

('A', 'B')


In [17]:
#print(my_tuple2)  # This line will not be executed because the previous line raises an error

In [18]:
print(my_tuple2)  # This line will not be executed because the previous line raises an error

('A', 'B')


In [19]:
print(my_tuple2[0])  #

A


In [20]:
# creating an empty tuple
empty_tuple = ()
print(empty_tuple)

()


In [21]:
# creating a tuple with one element
single_element_tuple = (42,)
print(single_element_tuple)


(42,)


In [22]:
# dictionaries
# A dictionary is a collection of key-value pairs in Python, where each key is unique and
# is used to access its corresponding value. Dictionaries are defined using curly braces {} and the key-value pairs are separated by colons (:).
my_dict = {"name": "Alice", "age": 30, "city": "New York"}
# I will print the my_dict to the console
print(my_dict)
# the output should be {'name': 'Alice', 'age': 30, 'city': 'New York'}


{'name': 'Alice', 'age': 30, 'city': 'New York'}


In [23]:
# print one element from the dictionary using its key
print(my_dict["name"])  # This will print "Alice" because it is the value associated with the key "name" in the my_dict dictionary


Alice


In [24]:
phonebook = {
    "Alice": "555-1234",
    "Bob": "555-5678",
    "Charlie": "555-9012"
}
# I will print the phonebook dictionary to the console
print(phonebook)
# the output should be {'Alice': '555-1234', 'Bob': '555-5678', 'Charlie': '555-9012'}


{'Alice': '555-1234', 'Bob': '555-5678', 'Charlie': '555-9012'}


In [25]:
# print an eelment from the phonebook dictionary using its key
print(phonebook["Bob"])  # This will print "555-5678" because it is the value associated with the key "Bob" in the phonebook dictionary


555-5678


In [26]:
# to delete a key-value pair from a dictionary, you can use the del statement followed by the dictionary name and the key you want to delete in square brackets
del phonebook["Charlie"]
# I will print the phonebook dictionary again to see the change
print(phonebook)

{'Alice': '555-1234', 'Bob': '555-5678'}


In [27]:
# loops
# A loop is a programming construct that allows you to repeat a block of code multiple times.
# for in range loop
for i in range(5):
    print(i)
# the output should be 0, 1, 2, 3, 4 each on a new line because the range(5) function generates a sequence of numbers from 0 to 4 (inclusive) and the for loop iterates over that sequence, printing each number on a new line.


0
1
2
3
4


In [28]:
names = ["A", "B", "C" ]
for name in names:
    # the output should be A, B, C each on a new line because the for loop iterates over the names list and prints each name on a new line
    print(name)


A
B
C


In [29]:
for i in range(len(names)):
    # the output should be A, B, C each on a new line because the for loop iterates over the indices of the names list and prints the element at each index on a new line
    print(names[i])

print("-----")

A
B
C
-----


In [30]:
# using the enumerate function to loop through a list with both the index and the value
for index, name in enumerate(names):
    # the output should be 0 A, 1 B, 2 C each on a new line because the enumerate function returns both the index and the value of each element in the names list, and the for loop iterates over that and prints both the index and the name on a new line
    print(index, name)

    

0 A
1 B
2 C


In [31]:
# We can also loop through a dictionary in different ways.
# 1. Looping through the keys of the dictionary
phonebook = {"A": "12-37", "B": "34-23"}
for key in phonebook:
    print(key)



A
B


In [32]:
# to get the value associated with each key, you can use the key to access the value in the dictionary
for key in phonebook:
    value = phonebook[key]
    print(key, value)



A 12-37
B 34-23


In [33]:
# for key, value in phonebook.items():
#     print(key, value)
for key, value in phonebook.items():
    print(key, value)

A 12-37
B 34-23


In [34]:
# just get the values of the dictionary
for value in phonebook.values():
    print(value)    

12-37
34-23


In [35]:
## numpy
import numpy as np

# creating a numpy array from a list\
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [36]:
x = np.array([1, 2, 3])
# this is a 1D array with 3 elements
print(x)

[1 2 3]


In [37]:
a = np.array([[1, 2, 3]])
# this is a 2D array with 1 row and 3 columns
print(a)

[[1 2 3]]


In [38]:
y = np.array([[3, 4, 5]])
# this is a 2D array with 1 row and 3 columns
print(y)

[[3 4 5]]


In [39]:
z = np.array([[6, 7],
              [8, 9]])

# this is a 2D array with 2 rows and 2 columns
print(z)

[[6 7]
 [8 9]]


In [40]:
print(x.shape)
# this will print the shape of the x array, which is (3,) because it is a 1D array with 3 elements

(3,)


In [41]:
print(y.shape)
# this will print the shape of the y array, which is (1, 3) because it is a 2D array with 1 row and 3 columns

(1, 3)


In [42]:
print()
print(z.shape)
# this will print the shape of the z array, which is (2, 2) because it is a 2D array with 2 rows and 2 columns


(2, 2)


In [ ]:
x = np.array([[1, 2],
              [3, 4],
              [5, 6]]) # this is a 2D array with 3 rows and 2 columns
# so it will look like this:
# [[1 2]
#  [3 4]
#  [5 6]]
np.max(x)  # This will return the maximum value in the x array, which is 6
# the axis will determine the direction of the operation. If axis=0, it will operate along the columns (down the rows), and if axis=1, it will operate along the rows (across the columns).
# axis - 0 means to operate along the columns (down the rows), 
# and axis - 1 means to operate along the rows (across the columns). Since x is a 1D array, the axis parameter is not applicable in this case.


np.int64(6)

In [ ]:
print(np.max(x, axis=1)) # this will return the maximum value of each row in the x array, which is [2, 4, 6]
# Since x = [[1 2],
#            [3 4],
#            [5 6]]
# → np.max(x, axis=1) = [2 4 6] 
# # the axis=1 means to operate along the rows (across the columns), 
# so it will return the maximum value of each row in the x array, 
# which are 2 for the first row, 4 for the second row, and 6 for the third row.


[2 4 6]


In [ ]:
print(np.max(x, axis=0)) 
# this will return the maximum value of each column in the x array, which is [5, 6]
# Since x = [[1 2],
#            [3 4],
#            [5 6]]
# → np.max(x, axis=0) = [5 6]
# # the axis=0 means to operate along the columns (down the rows), 
# so it will return the maximum value of each column in the x array, 
# which are 5 for the first column and 6 for the second column.


[5 6]


In [ ]:
# Now, let's check the shape of that result.
print(np.max(x, axis=1).shape)
# the shape is (3,) because the result is a 1D array with 3 elements, which are the maximum values of each row in the x array.

(3,)


In [ ]:
print(np.max(x, axis=1, keepdims=True))
# the keepdims = True means to keep the dimensions of the original array, 
# so the result will be a 2D array with 3 rows and 1 column, 
# instead of a 1D array with 3 elements. The output will be:
# [[2]
#  [4]
#  [6]]

[[2]
 [4]
 [6]]


In [52]:
# Let's check its shape:
print(np.max(x, axis=1, keepdims=True).shape)

(3, 1)


In [53]:
# matrix operations
# Create two 2D NumPy arrays (matrices)
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[3, 3],
              [3, 3]])


In [54]:
print("-----")
print(A)
print(B)

-----
[[1 2]
 [3 4]]
[[3 3]
 [3 3]]


In [55]:
print(A * B)  # This will perform element-wise multiplication of A and B, resulting in [[3, 6], [9, 12]]

[[ 3  6]
 [ 9 12]]


In [56]:
print("-----")
print(A + B)

-----
[[4 5]
 [6 7]]


In [58]:
print(A @ B)
# This will perform matrix multiplication of A and B, resulting in [[9, 9], [21, 21]]

[[ 9  9]
 [21 21]]


In [59]:
# Create two 1D NumPy arrays (vectors).
u = np.array([1, 2, 3])
v = np.array([1, 10, 100])

In [60]:
print("-----")
print(u)
print(v)

-----
[1 2 3]
[  1  10 100]


In [61]:
print(np.dot(u, v)) 
# This will compute the dot product of u and v, which is 1*1 + 2*10 + 3*100 = 321

321


In [62]:
print(u.dot(v)) 
# This will also compute the dot product of u and v, which is 1*1 + 2*10 + 3*100 = 321

321


In [63]:
# Create a 2D NumPy array (matrix) with shape (3, 2) → 3 rows, 2 columns
W = np.array([[1, 2],
              [3, 4],
              [5, 6]])
# Let's check the shapes of our vectors/matrices.
print(v.shape)   # (3,) → a 1D vector with 3 elements
print(W.shape)   # (3, 2) → a matrix with 3 rows and 2 columns


(3,)
(3, 2)


In [ ]:
np.dot(v, W)
# This will perform the dot product of the 1D vector v and the 2D matrix W,
#  resulting in a new 1D vector with 2 elements.
#  The output will be [1*1 + 10*3 + 100*5, 1*2 + 10*4 + 100*6] = [531, 642]
# so this is v 1d array multiplying it self against each column of W, resulting in a new 1D array with 2 elements, which are the results of the dot product of v and W.


array([531, 642])

In [ ]:
print(np.dot(v, W).shape) 
# the shape of the result is (2,) because the result is a 1D array with 2 elements, 
# which are the results of the dot product of v and W.


(2,)


In [ ]:
# print(np.dot(W, v))
# This will perform the dot product of the 2D matrix W and the 1D vector v,
# resulting in a new 1D vector with 3 elements.
# this fails becuase the number of columns in W (2) does not match the number of elements in v (3), so the dot product cannot be computed.


In [73]:

# v = np.array([1, 10, 100])
# W = np.array([[1, 3, 5],
#               [2, 4, 6]])
# print(W.T) # this does not work because the number of columns in W.T (3) does not match the number of elements in v (3), so the dot product cannot be computed. The dot product of W.T and v is not defined because the inner dimensions do not match.

# print(np.dot(W.T, v))
# this does not work because the number of columns in W.T (3) does not match the number of elements in v (3), so the dot product cannot be computed. The dot product of W.T and v is not defined because the inner dimensions do not match.
# the dot product of W.T and v is not defined because the inner dimensions do not match. The number of columns in W.T (3) does not match the number of elements in v (3), so the dot product cannot be computed.

In [76]:
# Shape = (3, 4) → 3 rows, 4 columns
x = np.random.random((3, 4)) # this will create a 2D array with 3 rows and 4 columns, filled with random values between 0 and 1
print("-----")

-----


In [77]:
print("-----")
print(x)

-----
[[0.15222354 0.43722548 0.39147249 0.47715062]
 [0.13258258 0.16788128 0.85464586 0.57825829]
 [0.92937011 0.82336291 0.19903402 0.17019433]]


In [ ]:
print(x[:]) # copies the entire array x, creating a new array that is a copy of x. The output will be the same as x, which is a 2D array with 3 rows and 4 columns filled with random values between 0 and 1.
# this will create a new array that is a copy of the original x array, containing all the same elements. The output will be the same as x, which is a 2D array with 3 rows and 4 columns filled with random values between 0 and 1.

[[0.15222354 0.43722548 0.39147249 0.47715062]
 [0.13258258 0.16788128 0.85464586 0.57825829]
 [0.92937011 0.82336291 0.19903402 0.17019433]]


In [ ]:
print(x[np.array([0, 2]), :])
# np.array([0, 2]) creates an index array → [0, 2].
# The colon (:) means all columns.
# So this selects rows 0 and 2, and all their columns.

[[0.15222354 0.43722548 0.39147249 0.47715062]
 [0.92937011 0.82336291 0.19903402 0.17019433]]


In [81]:
print(x[1, 1:3])
# this will select the element in the second row (index 1)
#  and the columns from index 1 to index 3 (exclusive), 
# which are the elements in the second row and the second and third columns of the x array.
#  The output will be a 1D array containing those selected elements.


[0.16788128 0.85464586]


In [83]:
print(x[x > 0.5])
# this will create a new array that contains only the elements 
# of x that are greater than 0.5. 
# The output will be a 1D array containing those selected elements 
# from the x array that are greater than 0.5.
# so this is a filtered if conditional statement that creates a new array with only the elements of x that satisfy the condition of being greater than 0.5. The output will be a 1D array containing those selected elements from the x array that are greater than 0.5.


[0.85464586 0.57825829 0.92937011 0.82336291]
